apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mlflow
spec:
  template:
    spec:
      containerConcurrency: 80
      containers:
        - image: us-central1-docker.pkg.dev/turbiner/mlflow/mlflow:1.0.3
          ports:
            - containerPort: 8000
              name: http1
          env:
            - name: DEFAULT_ARTIFACT_ROOT
              value: gs://turbiner-mlflow-artifacts
            - name: MLFLOW_DB_URI
              valueFrom:
                secretKeyRef:
                  name: MLFLOW_DB_URI
                  key: 'latest'
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
      serviceAccountName: mlflow-runner@turbiner.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
