name: Deploy flows to Prefect and Docker image to Cloud Run

on:
  workflow_dispatch:
#   push:
#     branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.3"
    - name: Generate requirements.txt
      run: poetry export -f requirements.txt -o requirements.txt --with etl
    - name: Get project version
      id: project_version
      run: echo "VERSION=$(poetry version --short);" >> $GITHUB_OUTPUT
    - name: Print project version
      run: echo ${{ vars.DOCKER_ETL__IMAGE_NAME }}:${{ steps.project_version.outputs.VERSION }}
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag $DOCKER_ETL__IMAGE_NAME:${{ steps.project_version.outputs.VERSION }}
